---

install_dns_domain_name: "{{ dns_domain_name | default('example.com') }}"

install_mssql_username: "{{ mssql_username | default('sqladmin') }}"
install_mssql_password: "{{ mssql_password | default('') }}"

install_sql_server_instance_name: "{{ sql_server_instance_name | default('MSSQLSERVER') }}"
install_sql_server_sys_admin_accounts:
  - "{{ install_mssql_username }}"
install_sql_server_features:
  - SQLENGINE
  - FullText
  - Replication
install_sql_server_svc_account_name: "{{ sql_server_svc_account_name | default('SASQLSvcAccount') }}"
install_sql_server_agt_svc_account_name: "{{ sql_server_agt_svc_account_name | default('SAAgtSvcAccount') }}"
install_sql_server_svc_accounts_password: "{{ sql_server_svc_accounts_password | default('') }}"
install_sql_server_local_users: "{{ sql_server_local_users | default(false) }}"

install_sql_server_svc_account: "{{ install_domain_prefix | upper }}\\{{ install_sql_server_svc_account_name }}"
install_sql_server_agt_svc_account: "{{ install_domain_prefix | upper }}\\{{ install_sql_server_agt_svc_account_name }}"

install_iso_path: "{{ iso_path | default(ansible_env.TEMP + '\\sql2019.iso') }}"
install_iso_url: "{{ iso_url | default('\\\\file_server\\sql2019.iso') }}"
