---
- name: setup first node
  ansible.builtin.include_tasks: first_node.yml
  when: alwayson_first_node

- name: setup other nodes
  ansible.builtin.include_tasks: other_nodes.yml
  when: not alwayson_first_node
