---

- name: add a powershell module
  community.windows.win_psmodule:
    name: ActiveDirectoryDsc
    state: present

- name: enable windows features
  ansible.windows.win_dsc:
    resource_name: WindowsFeature
    Name: "{{ item }}"
    IncludeAllSubFeature: True
    Ensure: Present
  register: install_ad
  ignore_errors: true
  loop:
    - RSAT-AD-PowerShell

- name: add computer object
  ansible.windows.win_dsc:
    resource_name: ADComputer
    Ensure: Present
    ComputerName: "{{ sql_server_availability_group_listener_name }}"
    DnsHostName: "{{ sql_server_availability_group_listener_name }}.{{ dns_domain_name }}"
    Path: '{{ join_ou_path | default("") }}'
    Description: "AlwaysOn Availability Group Listener Account"
    EnabledOnCreation: False
    DomainController: "{{ windows_ad_server_ip }}"
    PsDscRunAsCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    PsDscRunAsCredential_password: "{{ domain_admin_password }}"

- name: add full control to cluster name object
  ansible.windows.win_dsc:
    resource_name: ADObjectPermissionEntry
    Ensure: Present
    Path: 'CN={{ sql_server_availability_group_listener_name }},{{ join_ou_path }}'
    IdentityReference: '{{ dns_domain_name }}\{{ cluster_name }}$'
    ActiveDirectoryRights: 'GenericAll'
    AccessControlType: 'Allow'
    ObjectType: '00000000-0000-0000-0000-000000000000'
    ActiveDirectorySecurityInheritance: 'None'
    InheritedObjectType: '00000000-0000-0000-0000-000000000000'
    PsDscRunAsCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    PsDscRunAsCredential_password: "{{ domain_admin_password }}"

- block:
    - name: add a powershell module
      community.windows.win_psmodule:
        name: DnsServerDsc
        state: present

    - name: Create DNS A record for AG
      ansible.windows.win_dsc:
        resource_name: DnsRecordA
        Ensure: Present
        Name: "{{ sql_server_availability_group_listener_name }}"
        IPv4Address: "{{ sql_server_availability_group_ipv4_address }}"
        ZoneName: "{{ dns_domain_name }}"
  delegate_to: '{{ windows_ad_server_ip }}'
  vars:
    ansible_user: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    ansible_password: "{{ domain_admin_password }}"

- name: update ACL for DNS record of the CMO
  ansible.windows.win_dsc:
    resource_name: ADObjectPermissionEntry
    Ensure: Present
    Path: 'DC={{ sql_server_availability_group_listener_name }},DC={{ dns_domain_name }},cn=MicrosoftDNS,DC=DomainDnsZones,DC={{ dns_domain_name.split(".")[0] }},DC={{ dns_domain_name.split(".")[1] }}'
    IdentityReference: '{{ dns_domain_name }}\{{ cluster_name }}$'
    ActiveDirectoryRights: 'GenericAll'
    AccessControlType: 'Allow'
    ObjectType: '00000000-0000-0000-0000-000000000000'
    ActiveDirectorySecurityInheritance: 'None'
    InheritedObjectType: '00000000-0000-0000-0000-000000000000'
    PsDscRunAsCredential_username: "{{ domain_admin_username }}@{{ dns_domain_name }}"
    PsDscRunAsCredential_password: "{{ domain_admin_password }}"
