---
- name: add a powershell module
  community.windows.win_psmodule:
    name: ActiveDirectoryDsc
    state: present

- name: enable windows features
  ansible.windows.win_dsc:
    resource_name: WindowsFeature
    Name: "{{ item }}"
    IncludeAllSubFeature: true
    Ensure: Present
  register: install_ad
  failed_when: false
  loop:
    - RSAT-AD-PowerShell

- name: add computer object
  ansible.windows.win_dsc:
    resource_name: ADComputer
    Ensure: Present
    ComputerName: "{{ ad_availability_group_sql_server_availability_group_listener_name }}"
    DnsHostName: "{{ ad_availability_group_sql_server_availability_group_listener_name }}.{{ ad_availability_group_dns_domain_name }}"
    Path: '{{ ad_availability_group_join_ou_path | default("") }}'
    Description: AlwaysOn Availability Group Listener Account
    EnabledOnCreation: false
    DomainController: "{{ ad_availability_group_windows_ad_server_ip }}"
    PsDscRunAsCredential_username: "{{ domain_admin_username }}@{{ ad_availability_group_dns_domain_name }}"
    PsDscRunAsCredential_password: "{{ domain_admin_password }}"

- name: add full control to cluster name object
  ansible.windows.win_dsc:
    resource_name: ADObjectPermissionEntry
    Ensure: Present
    Path: CN={{ ad_availability_group_sql_server_availability_group_listener_name }},{{ ad_availability_group_join_ou_path }}
    IdentityReference: "{{ ad_availability_group_dns_domain_name }}\\{{ ad_availability_group_cluster_name }}$"
    ActiveDirectoryRights: GenericAll
    AccessControlType: Allow
    ObjectType: "00000000-0000-0000-0000-000000000000"
    ActiveDirectorySecurityInheritance: None
    InheritedObjectType: "00000000-0000-0000-0000-000000000000"
    PsDscRunAsCredential_username: "{{ domain_admin_username }}@{{ ad_availability_group_dns_domain_name }}"
    PsDscRunAsCredential_password: "{{ domain_admin_password }}"

- name: create DNS A record
  block:
    - name: add a powershell module
      community.windows.win_psmodule:
        name: DnsServerDsc
        state: present

    - name: Create DNS A record for AG
      ansible.windows.win_dsc:
        resource_name: DnsRecordA
        Ensure: Present
        Name: "{{ ad_availability_group_sql_server_availability_group_listener_name }}"
        IPv4Address: "{{ ad_availability_group_sql_server_availability_group_ipv4_address }}"
        ZoneName: "{{ ad_availability_group_dns_domain_name }}"
  delegate_to: "{{ ad_availability_group_windows_ad_server_ip }}"
  vars:
    ansible_user: "{{ domain_admin_username }}@{{ ad_availability_group_dns_domain_name }}"
    ansible_password: "{{ domain_admin_password }}"

- name: update ACL for DNS record of the CMO
  ansible.windows.win_dsc:
    resource_name: ADObjectPermissionEntry
    Ensure: Present
    Path: >-
      DC={{ ad_availability_group_sql_server_availability_group_listener_name }},
      DC={{ ad_availability_group_dns_domain_name }},
      cn=MicrosoftDNS,
      DC=DomainDnsZones,
      DC={{ ad_availability_group_dns_domain_name.split(".")[0] }},
      DC={{ ad_availability_group_dns_domain_name.split(".")[1] }}
    IdentityReference: "{{ ad_availability_group_dns_domain_name }}\\{{ ad_availability_group_cluster_name }}$"
    ActiveDirectoryRights: GenericAll
    AccessControlType: Allow
    ObjectType: "00000000-0000-0000-0000-000000000000"
    ActiveDirectorySecurityInheritance: None
    InheritedObjectType: "00000000-0000-0000-0000-000000000000"
    PsDscRunAsCredential_username: "{{ domain_admin_username }}@{{ ad_availability_group_dns_domain_name }}"
    PsDscRunAsCredential_password: "{{ domain_admin_password }}"
