---

alwayson_common_dns_domain_name: "{{ dns_domain_name | default('example.com') }}"

alwayson_common_mssql_username: "{{ mssql_username | default('sqladmin') }}"
alwayson_common_mssql_password: "{{ mssql_password | default('') }}"

alwayson_common_sql_server_instance_name: "{{ sql_server_instance_name | default('MSSQLSERVER') }}"

alwayson_common_sql_server_svc_account_name: "{{ sql_server_svc_account_name | default('SASQLSvcAccount') }}"
alwayson_common_sql_server_agt_svc_account_name: "{{ sql_server_agt_svc_account_name | default('SAAgtSvcAccount') }}"
alwayson_common_sql_server_local_users: "{{ sql_server_local_users | default(false) }}"

alwayson_common_sql_server_svc_account: "{{ alwayson_common_domain_prefix | upper }}\\{{ alwayson_common_sql_server_svc_account_name }}"
alwayson_common_sql_server_agt_svc_account: "{{ alwayson_common_domain_prefix | upper }}\\{{ alwayson_common_sql_server_agt_svc_account_name }}"
alwayson_common_cluster_svc_account: "{{ cluster_svc_account | default('NT SERVICE\\ClusSvc') }}"
