---
- name: add a powershell module
  community.windows.win_psmodule:
    name: ActiveDirectoryDsc
    state: present

- name: enable windows feature
  ansible.windows.win_dsc:
    resource_name: WindowsFeature
    Name: RSAT-AD-PowerShell
    IncludeAllSubFeature: true
    Ensure: Present
  register: install_ad
  failed_when: false

- name: Add windows group
  microsoft.ad.group:
    name: "{{ sql_users_sql_server_users_group_name }}"
    scope: global

- name: add domain users
  ansible.windows.win_dsc:
    resource_name: ADUser
    UserName: "{{ item }}"
    UserPrincipalName: "{{ item }}@{{ sql_users_dns_domain_name }}"
    Password_username: "{{ item }}"
    Password_password: "{{ sql_users_sql_server_svc_accounts_password }}"
    DomainName: "{{ sql_users_dns_domain_name }}"
    Credential_username: "{{ domain_admin_username }}@{{ sql_users_dns_domain_name }}"
    Credential_password: "{{ domain_admin_password }}"
    Enabled: true
    PasswordNeverExpires: true
    ChangePasswordAtLogon: false
    GivenName: "{{ item }}"
    Surname: user
    Company: AnsibleByRedHat
    EmailAddress: "{{ item }}@{{ sql_users_dns_domain_name }}"
    Ensure: Present
  loop: "{{ [sql_users_sql_server_svc_account_name, sql_users_sql_server_agt_svc_account_name] | unique }}"

- name: add domain users to sql group
  ansible.windows.win_dsc:
    resource_name: ADGroup
    GroupName: "{{ sql_users_sql_server_users_group_name }}"
    MembersToInclude: "{{ [sql_users_sql_server_svc_account_name, sql_users_sql_server_agt_svc_account_name] | unique }}"
    Credential_username: "{{ domain_admin_username }}@{{ sql_users_dns_domain_name }}"
    Credential_password: "{{ domain_admin_password }}"
