---
- name: create SQL users group
  ansible.windows.win_group:
    name: "{{ sql_users_sql_server_users_group_name }}"
    description: "{{ sql_users_sql_server_users_group_name }}"
    state: present

- name: set up SQL users
  ansible.windows.win_user:
    name: "{{ item }}"
    password: "{{ sql_users_sql_server_svc_accounts_password }}"
    password_never_expires: true
    state: present
    groups:
      - "{{ sql_users_sql_server_users_group_name }}"
  loop: "{{ [sql_users_sql_server_svc_account_name, sql_users_sql_server_agt_svc_account_name] | unique }}"
