---
- name: domain users
  ansible.builtin.include_tasks: domain.yml
  run_once: true
  when: not sql_users_sql_server_local_users

- name: local users
  ansible.builtin.include_tasks: local.yml
  when: sql_users_sql_server_local_users
