---
- name: Install required DSC modules
  community.windows.win_psmodule:
    name: "{{ item }}"
    state: present
  loop:
    - NetworkingDsc
    - SqlServerDsc

- name: set up sqladmin user
  ansible.windows.win_user:
    name: "{{ install_mssql_username }}"
    password: "{{ install_mssql_password }}"
    password_never_expires: true
    state: present
    groups:
      - Administrators

- name: install .Net
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: true
    include_management_tools: true
  with_items:
    - NET-Framework-Core
    - NET-Framework-Features
  register: install_dotnet
  until: install_dotnet is success
  delay: 3
  retries: 5

- name: check ISO file
  ansible.windows.win_stat:
    path: "{{ install_iso_path }}"
  register: iso_file
  when: (":" in install_iso_path)

- name: download iso
  ansible.builtin.include_tasks: download_iso.yml
  when: (":" in install_iso_path) and (not iso_file.stat.exists)

- name: mount iso and install
  block:
    - name: mount iso
      community.windows.win_disk_image:
        image_path: "{{ install_iso_path }}"
        state: present
      register: disk_image_out
      until: disk_image_out is success
      delay: 3
      retries: 5

    - name: install SQL Server
      ansible.windows.win_dsc:
        resource_name: SqlSetup
        InstanceName: "{{ install_sql_server_instance_name }}"
        SourcePath: "{{ disk_image_out.mount_paths[0] }}"
        Features: '{{ install_sql_server_features | join(",") }}'
        InstallSharedDir: C:\Program Files\Microsoft SQL Server
        SQLSysAdminAccounts: "{{ install_sql_server_sys_admin_accounts }}"
        SQLSvcAccount_username: "{{ install_sql_server_svc_account }}"
        SQLSvcAccount_password: "{{ install_sql_server_svc_accounts_password }}"
        AgtSvcAccount_username: "{{ install_sql_server_agt_svc_account }}"
        AgtSvcAccount_password: "{{ install_sql_server_svc_accounts_password }}"
        SecurityMode: SQL
        SAPwd_username: sa
        SAPwd_password: "{{ install_mssql_password }}"
      register: sql_install

  always:
    - name: unmount iso
      community.windows.win_disk_image:
        image_path: "{{ install_iso_path }}"
        state: absent

- name: enable tcp on SQL server instance
  ansible.windows.win_dsc:
    resource_name: SqlProtocol
    InstanceName: "{{ install_sql_server_instance_name }}"
    ProtocolName: TcpIp
    Enabled: true

- name: enable tcp port on SQL server instance
  ansible.windows.win_dsc:
    resource_name: SqlProtocolTcpIP
    InstanceName: "{{ sql_server_instance_name }}"
    IpAddressGroup: IPAll
    TCPPort: 1433
    Enabled: true

- name: Open port for MSSQL
  ansible.windows.win_dsc:
    resource_name: Firewall
    ensure: Present
    name: MSSQL
    enabled: true
    localport: 1433
    action: Allow
    direction: Inbound
    protocol: TCP
