---
- name: Install required DSC modules
  community.windows.win_psmodule:
    name: "{{ item }}"
    state: present
  loop:
    - NetworkingDsc
    - SqlServerDsc

- name: set up sqladmin user
  ansible.windows.win_user:
    name: "{{ mssql_username }}"
    password: "{{ mssql_password }}"
    password_never_expires: true
    state: present
    groups:
      - Administrators

- name: install .Net
  ansible.windows.win_feature:
    name:
      - NET-Framework-Core
      - NET-Framework-Features
    state: present
    include_sub_features: true
    include_management_tools: true
  register: install_dotnet
  until: install_dotnet is success
  delay: 3
  retries: 5

- name: check ISO file
  ansible.windows.win_stat:
    path: "{{ iso_path }}"
  register: iso_file
  when: (":" in iso_path)

- name: download iso
  ansible.builtin.include_tasks: download_iso.yml
  when: (":" in iso_path) and (not iso_file.stat.exists)

- block:
    - name: mount iso
      community.windows.win_disk_image:
        image_path: "{{ iso_path }}"
        state: present
      register: disk_image_out
      until: disk_image_out is success
      delay: 3
      retries: 5

    - name: install SQL Server
      ansible.windows.win_dsc:
        resource_name: SqlSetup
        InstanceName: '{{ sql_server_instance_name }}'
        SourcePath: '{{ disk_image_out.mount_paths[0] }}'
        Features: '{{ sql_server_features | join(",") }}'
        InstallSharedDir: 'C:\Program Files\Microsoft SQL Server'
        SQLSysAdminAccounts: '{{ sql_server_sys_admin_accounts }}'
        SQLSvcAccount_username: '{{ sql_server_svc_account }}'
        SQLSvcAccount_password: '{{ sql_server_svc_accounts_password }}'
        AgtSvcAccount_username: '{{ sql_server_agt_svc_account }}'
        AgtSvcAccount_password: '{{ sql_server_svc_accounts_password }}'
        SecurityMode: SQL
        SAPwd_username: sa
        SAPwd_password: '{{ mssql_password }}'
      register: sql_install

  always:
    - name: unmount iso
      community.windows.win_disk_image:
        image_path: "{{ iso_path }}"
        state: absent

- name: enable tcp protocol SQL server instance
  ansible.windows.win_dsc:
    resource_name: SqlProtocol
    InstanceName: '{{ sql_server_instance_name }}'
    ProtocolName: TcpIp
    Enabled: True

- name: enable tcp port on SQL server instance
  ansible.windows.win_dsc:
    resource_name: SqlProtocolTcpIP
    InstanceName: '{{ sql_server_instance_name }}'
    IpAddressGroup: IPAll
    TCPPort: 1433
    Enabled: True

- name: Open port for MSSQL
  ansible.windows.win_dsc:
    resource_name: Firewall
    ensure: Present
    name: MSSQL
    enabled: True
    localport: 1433
    action: Allow
    direction: Inbound
    protocol: TCP
